services:
  sqlserver:
    container_name: db_sqlserver2
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Sinclave1!
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    ports:
      - 1413:1433
    volumes:
      - data:/var/opt/mssql

volumes:
  data:
    driver: local
